export const BANK_SETUP = "BANK_SETUP";
export const GET_MATCHING_OFFERS = "GET_MATCHING_OFFERS";
export const SET_FILTER = "SET_FILTER";
export const SET_CUR_OFFER = "SET_CUR_OFFER";
export const GET_COUNTER_OFFERS_RECEIVED = "GET_COUNTER_OFFERS_RECEIVED";
export const GET_COUNTER_OFFERS_MADE = "GET_COUNTER_OFFERS_MADE";
export const ACCEPT_OFFER_STATUS = "ACCEPT_OFFER_STATUS";
